# Generated by Django 6.0 on 2026-01-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='othername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
