# Generated by Django 6.0 on 2026-01-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_categories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
